### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by kylemcdonald** [aguinet/usbtop#18] opened 2018-09-12 02:23 UTC
I think this might be a version mismatch? As far as I can tell I followed the instructions correctly. This is on Ubuntu 16.04.

```
kyle:~/Downloads$ sudo apt install -y libboost-dev libpcap-dev libboost-thread-dev libboost-system-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-dev is already the newest version (1.58.0.1ubuntu1).
libpcap-dev is already the newest version (1.7.4-2).
libboost-system-dev is already the newest version (1.58.0.1ubuntu1).
libboost-thread-dev is already the newest version (1.58.0.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
kyle:~/Downloads$ git clone https://github.com/aguinet/usbtop.git
Cloning into 'usbtop'...
remote: Counting objects: 173, done.
remote: Total 173 (delta 0), reused 0 (delta 0), pack-reused 173
Receiving objects: 100% (173/173), 29.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (114/114), done.
Checking connectivity... done.
kyle:~/Downloads$ cd usbtop/ ; mkdir build ; cd build
kyle:~/Downloads/usbtop/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Pcap include dirs set to /usr/include
-- Pcap library set to  /usr/lib/x86_64-linux-gnu/libpcap.so
-- Looking for pcap_breakloop
-- Looking for pcap_breakloop - found
-- Looking for pcap_datalink_name_to_val
-- Looking for pcap_datalink_name_to_val - found
-- Looking for pcap_datalink_val_to_name
-- Looking for pcap_datalink_val_to_name - found
-- Looking for pcap_findalldevs
-- Looking for pcap_findalldevs - found
-- Looking for pcap_freecode
-- Looking for pcap_freecode - found
-- Looking for pcap_get_selectable_fd
-- Looking for pcap_get_selectable_fd - found
-- Looking for pcap_lib_version
-- Looking for pcap_lib_version - found
-- Looking for pcap_list_datalinks
-- Looking for pcap_list_datalinks - found
-- Looking for pcap_open_dead
-- Looking for pcap_open_dead - found
-- Looking for pcap_set_datalink
-- Looking for pcap_set_datalink - found
-- Found PCAP: /usr/include  
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:15 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:15 (find_package)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kyle/Downloads/usbtop/build
kyle:~/Downloads/usbtop/build$ make -j`nproc`
Scanning dependencies of target usbtop
[ 10%] Building CXX object src/CMakeFiles/usbtop.dir/main.cpp.o
[ 30%] Building CXX object src/CMakeFiles/usbtop.dir/should_stop.cpp.o
[ 30%] Building CXX object src/CMakeFiles/usbtop.dir/console_output.cpp.o
[ 40%] Building CXX object src/CMakeFiles/usbtop.dir/usb_stats.cpp.o
[ 60%] Building CXX object src/CMakeFiles/usbtop.dir/tools.cpp.o
[ 60%] Building CXX object src/CMakeFiles/usbtop.dir/usb_device.cpp.o
[ 70%] Building CXX object src/CMakeFiles/usbtop.dir/usb_bus.cpp.o
[ 80%] Building CXX object src/CMakeFiles/usbtop.dir/buses.cpp.o
[ 90%] Building CXX object src/CMakeFiles/usbtop.dir/pcap_compat.cpp.o
[100%] Linking CXX executable usbtop
[100%] Built target usbtop
kyle:~/Downloads/usbtop/build$ sudo make install
[100%] Built target usbtop
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/sbin/usbtop
-- Set runtime path of "/usr/local/sbin/usbtop" to ""
kyle:~/Downloads/usbtop/build$ cd ../.. ; sudo usbtop
usbtop: error while loading shared libraries: libboost_thread.so.1.65.1: cannot open shared object file: No such file or directory
```

**Comment by NukeMania** [comment] 2018-09-12 17:42
#15 fixes problem

**Comment by aguinet** [comment] 2019-02-26 13:31
I merged this one (it took some time...). I also removed the boost thread/system dependency, so this might also fix this problem!

**Comment by aguinet** [comment] 2019-02-26 13:31
Please re-open if the problem is still there!

**Closed by aguinet** 2019-02-26 13:31 UTC
